repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        exclude: '^python/triton/runtime/.*'
        args: ["-d"]
        stages: [commit, push, manual]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        exclude: '^python/triton/runtime/.*'
        args: ["--version"]
        stages: [commit, push, manual]
exclude: |
  (?x)(
    ^include/triton/external/|
    ^python/triton/third_party/
  )
