name: Triton-Shared Plugin Testing

on:
  workflow_call:
    inputs:
      triton-ref:
        required: true
        type: string
      triton-shared-ref:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      triton-ref:
        required: true
        type: string
      triton-shared-ref:
        required: true
        type: string
      notify-on-failure:
        default: false
        type: boolean
      force-failure:
        default: false
        type: boolean


jobs:
  build_and_test_triton_shared:
    runs-on: ubuntu-latest

    steps:
    - name: Forcing Failure
      if: ${{ github.event.inputs.force-failure }}
      run: exit 1

    - name: Checkout Triton
      uses: actions/checkout@v4
      with:
        repository: 'openai/triton'
        ref: ${{ inputs.triton-ref }}
        path: triton
        submodules: 'recursive'

    - name: Checkout Triton-Shared
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.triton-shared-ref }}
        path: triton/third_party/triton_shared

    - name: Clear Triton Cache
      run: |
        rm -rf ~/.triton

    - name: Update PATH
      run: |
        echo "PATH=${HOME}/.local/bin:${PATH}" >> "${GITHUB_ENV}"

    - name: Check pre-commit
      run: |
        cd triton
        python3 -m pip install --upgrade pre-commit
        python3 -m pre_commit run --all-files --verbose

    - name: Build/Install Triton
      run: |
        export TRITON_CODEGEN_TRITON_SHARED=1
        cd triton/python
        python3 -m pip install --upgrade pip
        python3 -m pip install cmake==3.24
        python3 -m pip install ninja
        python3 -m pip uninstall -y triton
        python3 setup.py build
        python3 -m pip install --no-build-isolation -vvv '.[tests]'

    - name: Run shared middle-layer lit tests
      run: |
        python3 -m pip install lit
        cd triton/python
        LIT_TEST_DIR="build/$(ls build | grep -i cmake)/third_party/triton_shared/test"
        if [ ! -d "${LIT_TEST_DIR}" ]; then
          echo "Coult not find '${LIT_TEST_DIR}'" ; exit -1
        fi
        lit -v "${LIT_TEST_DIR}"

    - name: Report Failure
      if: ${{ failure() }}
      run: |
        gh --repo ${{ github.repository }} issue create  \
           --title "Rolling Build Failure $(date +'%Y-%m-%d')" \
           --body "(Rolling build failed)[${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}].\nTagging @manbearian that this job has failed"
      env:
        GH_TOKEN: ${{ github.token }}

        

